name: pianoza
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  box_transform: ^0.4.4
  croppy: ^1.3.6
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_box_transform: ^0.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sheet1.png
    - assets/sheet2.png
    
